# Generated by Django 4.2.6 on 2023-12-22 18:04

from django.db import migrations, models
import django.utils.timezone

# fmt: off

class Migration(migrations.Migration):
    dependencies = [
        ("baskets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basket",
            options={"verbose_name": "Basket", "verbose_name_plural": "Baskets"},
        ),
        migrations.AddField(
            model_name="basket",
            name="image",
            field=models.CharField(
                default="https://c.wallhere.com/photos/2c/db/2880x1800_px_Futurama_Memes_Philip_J_Fry-1275101.jpg!d"
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="price",
            field=models.FloatField(default=0, verbose_name="Price"),
        ),
        migrations.AlterField(
            model_name="basket",
            name="category",
            field=models.ManyToManyField(
                through="baskets.BasketCategory",
                to="baskets.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="date_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date-Time"
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="basket",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(db_index=True, max_length=100, verbose_name="Name"),
        ),
    ]

# fmt: on
