FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /opt/baskets

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip && \
    pip install -r requirements.txt && \
    pip install uvicorn

COPY . .

EXPOSE 8000

ENTRYPOINT ["bash", "celery_entrypoint.sh"]
